import Image from 'next/image';
import Link from 'next/link';
import CharacterSheet from '../components/CharacterSheet';
import pat_full from '../../public/characters/pat_full.svg';
import kid_pat from '../../public/characters/kid_pat.svg';

import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Patripples | Read',
	description: 'Patripples: ripples, mathematics, and more! Coming soon!',
};
export default function Character() {
	return (
		<main className={`main center height-full`}>
			<h1 className={`style-1 thin lowercase`}>phases of pat.</h1>
			<section className={`flex gap-large center`}>
				<p>
					(Incomplete - Phase One Pat cartoonization is NOT FINISHED - stats
					generated by ChatGPT following description of life/phases)
				</p>
				<CharacterSheet
					phase={'Phase One'}
					title={`The Seed Beneath the Concrete`}
					archetype={[`Dormant Mage`, `Watcher`]}
					age={[8, 18]}
					stats={{
						strength: 8,
						dexterity: 10,
						constitution: 9,
						intelligence: 14,

						wisdom: 13,
						charisma: 11,
					}}
					image={kid_pat}
					alt="Phase One Pat"
				/>
				{/*<CharacterSheet
					phase={'Phase Two'}
					title={`The Phoenix Without Fire`}
					archetype={[`Unproven Prodigy`, `Fractured Hero`]}
					age={[18, 28]}
					stats={{
						strength: 11,
						dexterity: 12,
						constitution: 10,
						intelligence: 15,

						wisdom: 12,
						charisma: 13,
					}}
					image={pat_full}
					alt="Phase Two Pat"
				/>*/}

				<CharacterSheet
					phase={'Phase Three'}
					title={`The Psilocybin Cartographer`}
					archetype={[`Explorer of Infinity`, `Mirror-Walker`]}
					age={[28, 32]}
					stats={{
						strength: 13,
						dexterity: 14,
						constitution: 13,
						intelligence: 17,

						wisdom: 16,
						charisma: 15,
					}}
					image={pat_full}
					alt="Phase Three Pat"
				/>
				{/*<CharacterSheet
					phase={'Phase Four'}
					title={`The Architect in Exile`}
					archetype={[`Rebel Scholar`, `Underground Alchemist`]}
					age={[32, 0]}
					stats={{
						strength: 14,
						dexterity: 15,
						constitution: 14,
						intelligence: 18,

						wisdom: 17,
						charisma: 16,
					}}
					image={pat_full}
					alt="Phase Four Pat"
				/>*/}
				{/*<CharacterSheet
					phase={'Phase Five'}
					title={`The Signal Fire`}
					archetype={[`Guiding Flame`, `Empathic Strategist`]}
					age={[32, 0]}
					stats={{
						strength: 15,
						dexterity: 16,
						constitution: 16,
						intelligence: 18,

						wisdom: 18,
						charisma: 18,
					}}
					image={pat_full}
					alt="Phase Five Pat"
				/>*/}
			</section>
		</main>
	);
}
